#!/bin/zsh
export DOTFILES_PATH=${0:a:h}
export DOTFILES_VENDOR_PATH="${DOTFILES_PATH}/vendor"
export DOTFILES_BIN_PATH="${DOTFILES_PATH}/bin"
export DOTFILES_CONFIG_PATH="${DOTFILES_PATH}/config"

[[ "$(uname)" == "Darwin" ]] && IS_MAC_OS=1 || IS_MAC_OS=0
[[ "$(uname)" == "Linux" ]] && IS_LINUX=1 || IS_LINUX=0

# polar night
export COLORS_NORD0=#2E3440
export COLORS_NORD1=#3B4252
export COLORS_NORD2=#434C5E
export COLORS_NORD3=#4C566A
# snow storm
export COLORS_NORD4=#D8DEE9
export COLORS_NORD5=#E5E9F0
export COLORS_NORD6=#ECEFF4
# frost
export COLORS_NORD7=#8FBCBB
export COLORS_NORD8=#88C0D0
export COLORS_NORD9=#81A1C1
export COLORS_NORD10=#5E81AC
# aurora
export COLORS_NORD11=#BF616A
export COLORS_NORD12=#D08770
export COLORS_NORD13=#EBCB8B
export COLORS_NORD14=#A3BE8C
export COLORS_NORD15=#B48EAD

